= Buildinfo Plugin
:latestRevision: 6.0.0
:toc:

NOTE: Version 5 of this plugin will only work with Gradle 5, JDK 8 and does not support Ivy or Subversion.

== Summary
This plugin adds information about the build, OS, CI process and SCM to the publish meta file (pom.xml) and
to the jar file. This helps to verify build artifacts.

== Usage
To use the Gradle Intershop Buildinfo plugin, include the following in your build script:

[source,groovy]
[subs=+attributes]
.build.gradle
----
plugins {
    id 'com.intershop.gradle.buildinfo' version '{latestRevision}'
}
----

== Project Extension 'buildinfo'
This plugin adds an extension *`buildinfo`* to the project.  This extension contains all plugin configurations.

=== Properties
[cols="10%,10%,10%,80%", width="90%, options="header"]
|===
|Property           | Type      | Default value | Description
|*noAdditionalJarInfo*        |`boolean`  | false         | If this value is true the build information is not stored in the jar file.  +
                                                  _This can be overwritten by the system or environment variable `NOJARINFO` or project property `noJarInfo`._
|*ModuleVendor*  |`String`   | ''            | The name of the vendor. +
                                                  This information is always added to the JAR if it is configured.
|===

== Example Build Information

=== Jar File
[source,properties]
[subs=+attributes]
.META-INF\MANIFEST.MF
----
Manifest-Version: 1.0
Created-By: 1.7.0_80-b15 (Oracle Corporation)
Build-Java-Version: 1.7.0_80
X-Compile-Source-JDK: 1.7
X-Compile-Target-JDK: 1.7
Implementation-Version: 10.0.0
Build-Status: integration
Built-By: gitlab-runner
Built-OS: Linux
Build-Date: 2016-03-26_17:06:24
Gradle-Version: 2.11
Gradle-RootProject: project
Module-Origin: https://buildserver.com/buildjob
SCM-change-info: c05817d
SCM-change-time: 20160326165513
SCM-branch-name: c05817d4cf68230258e1260183bfa26ee18c1cff
SCM-type: git
CI-build-host: buildhost.de
CI-build-url: https://buildhost.de/project/buildjob
CI-build-number: 1462
CI-build-job: buildjob
CI-build-time: 2016-02-22T15:09:15.508+01:00
----

=== Test
The integration tests using a test repositories. Therefore it is necessary to specify project properties for the test execution.

.Table Git test configuration
|===
|Test Property |Description | Value

|*giturl*    | URL of the test project      | Must be specified with environment variable *`GITURL`*
|*gituser*   | User name of Git test user   | Must be specified with environment variable *`GITUSER`*
|*gitpasswd* | Password for Git test user   | Must be specified with environment variable *`GITPASSWD`*
|===

== License

Copyright 2014-2016 Intershop Communications.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
